services:
  pg:
    image: docker.io/library/postgres:17.5
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U postgres -d postgres
      start_period: 5s
      start_interval: 5s
      interval: 10s
      timeout: 10s
      retries: 5
  front:
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      pg:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: package.json

volumes:
  pg_data:
